### ISSUE TITLE
Outreach to user base

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/brc-analytics#100]
We need to actively engage the former VEuPathDb community to:

- collect user scenarios
- understand which datasets need to be re-analyzed and put into genomic context

Immediate goals:

- [x] Aggregate emails of former VEuPathDb users we can get
- [x] Make sure they are aware of the Discourse help site
- [x] Push regular updates via social media channels

**Comment by scottcain** [comment]
I'm inclined to mark this done, although the last item is more of an "on going" thing.  I have approximately 500 emails to which I reached out individually. Of those, I got about 40 useful responses (a few "I'm retired", a few "I don't do that sort of thing", and several "I'll ask around and get back to you"
