### ISSUE TITLE
Create a fork of https://github.com/usegalaxy-eu/galaxy-social

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/brc-analytics#101]
Create a dedicated form of https://github.com/usegalaxy-eu/galaxy-social to automate outreach messaging for brc-analytics across all social media platforms

**Comment by hujambo-dunia** [comment]
[Configurations for BRC Analytics (PR 124)](https://github.com/usegalaxy-eu/galaxy-social/pull/124)
