### ISSUE TITLE
Add BRC-Analytics to the Galaxy-hub

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/brc-analytics#104]
It would be nice if we can create a project at https://galaxyproject.org. It could be just a symlink under `https://galaxyproject.org/projects/brc`. Here is one of such projects https://galaxyproject.org/projects/vgp/

**Comment by nekrut** [comment]
ping @dannon

**Comment by hujambo-dunia** [comment]
[Configurations for BRC Analytics](https://github.com/usegalaxy-eu/galaxy-social/pull/124)
