### ISSUE TITLE
"Copy to clipboard" button next to dbKey

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/brc-analytics#121]
Make it easy to "remember" dbKey by copying it into clipboard. For this add "copy ti clipboard" button next to "Assembly Version ID":

![image](https://github.com/user-attachments/assets/50de04ec-c91c-4118-a033-442c78600674)

**Comment by NoopDog** [comment]
@frano-m, can you add a copy to the clipboard functionality for "Assembly Version ID" on the detail pages. Thanks!
