### ISSUE TITLE
Change NCBI wording on "Roadmap" page

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/brc-analytics#123]
For the BRC Analytics "Our Plan" page, could you tweak the wording about Gene pages? How about:
“Work with NCBI on evolution of gene pages to contain information valuable for understanding the structure and function of genes from a wide range of eukaryotes including eukaryotic pathogens and vectors.”

We want to make it clear that our plan (at least for NCBI) is not to recapitulate the VEuPathDB pages, plus NCBI's goals are not specifically constrained to this set of organisms.

**Comment by NoopDog** [comment]
Complete ! Thx

**Comment by murphyte** [comment]
thanks!
