### ISSUE TITLE
Add carousel card for webinar video

### ISSUE THREAD

**Issue by scottcain** [galaxyproject/brc-analytics#127]
Card contents:

Last Friday (October 4), we hosted a video webinar Q&A about BRC Analytics where we discussed the future of the project and encouraged interested people to get involved in planning for next steps. A video of that webinar (w/auto-generated captions) is available on YouTube: https://youtu.be/dWK8AAk-Wns

**Comment by NoopDog** [comment]
@scottcain can you provide a title for the card?

**Comment by scottcain** [comment]
@NoopDog how about this for contents:

**Webinar video available**

On Friday, October 4, we hosted a video webinar Q&A about BRC Analytics where we discussed the future of the project and encouraged interested people to get involved in planning for next steps. A video of that webinar (w/auto-generated captions) is available on YouTube: https://youtu.be/dWK8AAk-Wns
