### ISSUE TITLE
Add carousel card for next webinar

### ISSUE THREAD

**Issue by scottcain** [galaxyproject/brc-analytics#141]
Card contents:

**Q&A Webinar on Wednesday, October 30th**

Please join us for another Q&A webinar on October 30th at 1 PM EDT/10 AM PDT/1700 UTC. We will focus primarily on the actual “analytics” part of the website: the Analyze buttons that will take users to workflows specific to the genome being worked on for various analysis types. Please join in and give feedback on our direction, as this is still early in development.

<a href="https://psu.zoom.us/j/99331380856?pwd=ktUUark52KveSfI824OPn5Rglfb3Wi.1">Zoom link</a>

**Comment by NoopDog** [comment]
Complete
