### ISSUE TITLE
Confirm matching of accessions between NCBI and UCSC Genome Browser

### ISSUE THREAD

**Issue by NoopDog** [galaxyproject/brc-analytics#194]
We are trying to match the response from the NCBI  /dataset/v2/genome/taxon API, e.g. 

https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/7165%2C5501/dataset_report?filters.assembly_source=refseq&filters.has_annotation=true&filters.exclude_paired_reports=true&filters.exclude_atypical=true&filters.assembly_level=scaffold&filters.assembly_level=chromosome&filters.assembly_level=complete_genome

to the UCSC Genome Browser [assemblyList.json](https://hgdownload.soe.ucsc.edu/hubs/BRC/assemblyList.json).

UCSC Uses `genBank` and `refSeq` as identifers in  the `assemblyList.json` and the NCPI returns an `accession` and `pairedAccession`.

#### Questions

1. Should we ever use `pairedAccession` in NCBI to match on or only `accession`?

2. Is the mapping algorithm listed below correct?

    1. Always use accession only on the NCBI side.
    2. If `accession` starts with GCA, match with `genBank` in assemblyList.json
    3. If `accession` starts with GCF match with `refSeq` n assemblyList.json
    4. If `accession` matches neither `genBank` nor `refSeq`, log as no match and skip. ( should this case ever happen)

**Comment by NoopDog** [comment]
From HIram

**Definitions:**  
'GenBank" assemblies are GCA accessions, 
'RefSeq" assemblies are GCF accessions. 
 A 'pairedAccession' means it is a haplotype of the assembly you are looking at.  A 'pairedAccession' is a completely different assembly. 

 I see accession mentioned: GCF_000277735.2, GCF_030566675.1, GCF_963525475.1 - I have none of those at UCSC

**Comment by nekrut** [comment]
> We are trying to match the response from the NCBI /dataset/v2/genome/taxon API, e.g.
> 
> https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/7165%2C5501/dataset_report?filters.assembly_source=refseq&filters.has_annotation=true&filters.exclude_paired_reports=true&filters.exclude_atypical=true&filters.assembly_level=scaffold&filters.assembly_level=chromosome&filters.assembly_level=complete_genome
> 
> to the UCSC Genome Browser [assemblyList.json](https://hgdownload.soe.ucsc.edu/hubs/BRC/assemblyList.json).
> 
> UCSC Uses `genBank` and `refSeq` as identifers in the `assemblyList.json` and the NCPI returns an `accession` and `pairedAccession`.
> 
> #### Questions
> 1. Should we ever use `pairedAccession` in NCBI to match on or only `accession`?
> 2. Is the mapping algorithm listed below correct?
>    
>    1. Always use accession only on the NCBI side.
>    2. If `accession` starts with GCA, match with `genBank` in assemblyList.json
>    3. If `accession` starts with GCF match with `refSeq` n assemblyList.json
>    4. If `accession` matches neither `genBank` nor `refSeq`, log as no match and skip. ( should this case ever happen)

1 and 4 are probably unnecessary since everything IS from NCBI. The only problem may be if UCSC does not yet have the browser for a given accession.

**Comment by NoopDog** [comment]
Answer:

1. Always use accession only on the NCBI side.
2. If accession starts with GCA, match with genBank in assemblyList.json
3. If accession starts with GCF match with refSeq n assemblyList.json
4. If accession matches neither genBank nor refSeq, log as no match and skip. ( should this case ever happen)

Thx All

**Comment by maximilianh** [comment]
> If accession matches neither genBank nor refSeq, log as no match and
skip. ( should this case ever happen)
... and alert us, so we can fix this.
