### ISSUE TITLE
Add standalone "Analyze"section to top nav

### ISSUE THREAD

**Issue by NoopDog** [galaxyproject/brc-analytics#65]
1. Remove the individual Analyze pages on the /organisms
2. Instead have the analyze links point to /analyze
3. On /analyze implement according to the mocks [here](https://www.figma.com/proto/wxBBIrZcZb6IhYSg4d8B7J/BRC-Analytics-Homepage?page-id=1%3A12&node-id=645-706&node-type=canvas&viewport=1631%2C498%2C0.42&t=ZQgDNl5gaAj4QGQy-8&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=357%3A559&hide-ui=1)
4. The cat image is a youtube [video](https://www.youtube.com/watch?v=k6fTVIR4GME)

**Comment by MillenniumFalconMechanic** [comment]
Not required.
