### ISSUE TITLE
Enable authentication passthrough from BRC to Galaxy workflow page

### ISSUE THREAD

**Issue by dannon** [galaxyproject/brc-analytics#77]
Users of https://brc.analytics.org must have accounts that will be shared with Galaxy instrances. Upon account creation the user should decide which Galaxy instance (.org, .eu. org.au is their "home" instance):

## Big picture
-  users sign for accounts at https://brc-analytics.org/. This account will also work as a Galaxy account (at https://brc.usegalaxy.org/ and https://usegalaxy.org/). 
- Can set as a local preference which Galaxy they want as default
- Need user preferences, that would for example allow customization of organism lists (favorite taxa) <- low priority at this point
- Can users link existing Galaxy accounts with the new BRC?
- Can these accounts be magically shared with MyNCBI?
## Discussion:
- Best solution: offer same login options for NCBI to Galaxy instances (top right)
- Galaxy allows us to associate new entity IDs to existing accounts
- AnVIL uses Next Auth. Once signed in via Google or MSFT, can link eRA commons ID.
- NIH wants to eventually switch to RAS. This is not immediately applicable because we’re not hosting protected datasets.
- ACTION: Dave R and Dannon put together a plan for how users will sign into BRC.Analytics and brc.usegalaxy.org or user selected Galaxy.

**Comment by nekrut** [comment]
# 9/26/2024 Update

For MVP1 (#107) we (@dannon @NoopDog ) decided not to create dedicated Galaxy accounts but instead:

- [ ] enable authentication via Google on .org
- [ ] Explain new users that they need to create new Galaxy accounts via Google
- [ ] Once brc-analytics.org accounts will be created we will link them to Galaxy

**Comment by nekrut** [comment]
see https://github.com/galaxyproject/galaxy/issues/19082

**Comment by nekrut** [comment]
Looks like this works.
