### ISSUE TITLE
Persistent help / feedback button

### ISSUE THREAD

**Issue by NoopDog** [galaxyproject/brc-analytics#81]
We could add a persistent help button in the current style to the site like:

<img width="354" alt="image" src="https://github.com/user-attachments/assets/2d0f348c-529a-4131-b2d1-94e58d7eccf8">

If we did so, where would it link to? One idea is to link to the current Google form for the [Migration Questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSdSj9QtrY1zdUF45V7zGDKY1qKlo8BbSgF0BPfKfSzRTlgsVg/viewform) 

A second option is to develop  a second Google form with questions like:

<img width="547" alt="image" src="https://github.com/user-attachments/assets/a43a4922-fbf7-4a2d-8d2b-f94a06fc6183">

**Comment by scottcain** [comment]
I think adding a standard feedback option like this is a good one, though I think the migration questionnaire is perhaps not a good thing to use. I like your other suggestion of a more generic form. Perhaps the easiest thing would be for me to create another form along these lines as a start and we can go from there.

**Comment by NoopDog** [comment]
From @scottcain [https://docs.google.com/forms/d/e/1FAIpQLSd8f5hrd1-ECgPUbS5dL9njoU1nvCSN5ukykKk9mF6WAyTh6A/viewform?](https://docs.google.com/forms/d/e/1FAIpQLSd8f5hrd1-ECgPUbS5dL9njoU1nvCSN5ukykKk9mF6WAyTh6A/viewform?usp=sf_link)

@frano-m, we can use this as the link.
