### ISSUE TITLE
Media presence: what platform?

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/brc-analytics#84]
- Which platform should be used?
- Can we use GalaxyProject linked in? Should we create a separate organization?

**Comment by nekrut** [comment]
We decided to create a separate linkdin organization

**Comment by scottcain** [comment]
LinkedIn community created: https://www.linkedin.com/company/brc-analytics/
Also, Bluesky account created: https://bsky.app/profile/brcanalytics.bsky.social

I'm thinking I'll create a mastodon account on mstdn.science and then fork the repo that automates the posting to all three at once.

**Comment by scottcain** [comment]
Created a mastodon account: https://mstdn.science/@brc_analytics
